### ISSUE TITLE
S3 Extension error

### ISSUE THREAD

**Issue by certi42** [Blackfynn/pathman#4]
For `S3Path` objects with request parameters in the URL, the `extension` property will return them in addition to the extension of the file.

For example:
```python
path = Path("https://base.s3.amazonaws.com/table.csv?token=whatever")
path.extension # '.csv?token=whatever'
```
In that example, `extension` should be just `.csv`.

**Comment by zduey** [comment]
tracking in click up: https://app.clickup.com/t/f0pf69
